{% set version = "15.0.1" %}

package:
  name: basswood-av
  version: {{ version }}

source:
  url: https://github.com/basswood-io/BasswoodAV/archive/refs/tags/{{ version }}.tar.gz
  sha256: 04c59fcb72e5f0f15b2f4787a6295c8baa9cdaa04f7e2febf57fc64b134794e1

build:
  number: 0
  skip: true  # [py<310]
  script:
    - {{ PYTHON }} -m pip install . -vv
  run_exports:
    - {{ pin_subpackage('basswood-av') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.1.0a                        # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config  # [not win]
  host:
    - python
    - pip
    - setuptools
    - cython >=3.1.0a
    - numpy
    - ffmpeg  {{ ffmpeg }}=lgpl*
  run:
    - python
    - pillow
    - numpy >=1.22

test:
  source_files:
    - tests
  requires:
    - ffmpeg * gpl*    # [py==311]
    - ffmpeg * lgpl*   # [py==312]
    - pytest
  commands:
    # Test FFmpeg codec availability
    - python -c "import bv; assert 'libx264' in bv.codecs_available"       # [py==311]
    - python -c "import bv; assert 'libx265' in bv.codecs_available"       # [py==311]
    - python -c "import bv; assert 'libx264' not in bv.codecs_available"   # [py==312]
    - python -c "import bv; assert 'libx265' not in bv.codecs_available"   # [py==312]
    - python -c "import bv; assert 'libopenh264' in bv.codecs_available"
    # Run the test suite
    - pytest tests
  imports:
    - bv
    - bv.audio
    - bv.video

about:
  home: https://github.com/basswood-io/BasswoodAV
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pythonic binding for the FFmpeg libraries.
  description: |
    We aim to provide all of the power and control of the underlying library,
    but manage the gritty details as much as possible.

extra:
  recipe-maintainers:
    - hmaarrfk
