{% set version = "15.1.0" %}

package:
  name: basswood-av
  version: {{ version }}

source:
  url: https://github.com/basswood-io/BasswoodAV/archive/refs/tags/{{ version }}.tar.gz
  sha256: 16ac91d7e717458822a5126e2b1a1bdde3e8808d124de19d0200ef7ff0941054

build:
  number: 0
  skip: true  # [py<310]
  script:
    - {{ PYTHON }} -m pip install . -vv
  run_exports:
    - {{ pin_subpackage('basswood-av') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.1.0a                        # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config  # [not win]
  host:
    - python
    - pip
    - setuptools
    - cython >=3.1.0a
    - numpy
    - ffmpeg  {{ ffmpeg }}=lgpl*
  run:
    - python
    - pillow
    - numpy >=1.22

{% set tests_to_skip = "_not_a_real_test" %}
# hmaarrfk - 2024/09
# Seems like this test fails with ppc64le when using emulation (not tested natively)
{% set tests_to_skip = tests_to_skip + " or test_generator_graph" %}              # [ppc64le]
{% set tests_to_skip = tests_to_skip + " or test_reformat_pixel_format_align" %}  # [ppc64le]

# Seems like this test fails with aarch... but only with the gpl variant... i can't
# figure it out .... hmaarrffk 2025/03
{% set tests_to_skip = tests_to_skip + " or test_generator_graph" %}              # [aarch64]

test:
  source_files:
    - tests
  requires:
    - ffmpeg * gpl*    # [py==311]
    - ffmpeg * lgpl*   # [py==312]
    - pytest
  commands:
    # Test FFmpeg codec availability
    - python -c "import bv; assert 'libx264' in bv.codecs_available"       # [py==311]
    - python -c "import bv; assert 'libx265' in bv.codecs_available"       # [py==311]
    - python -c "import bv; assert 'libx264' not in bv.codecs_available"   # [py==312]
    - python -c "import bv; assert 'libx265' not in bv.codecs_available"   # [py==312]
    - python -c "import bv; assert 'libopenh264' in bv.codecs_available"
    - pytest tests -k "not ({{ tests_to_skip }})"
  imports:
    - bv
    - bv.audio
    - bv.video

about:
  home: https://github.com/basswood-io/BasswoodAV
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pythonic binding for the FFmpeg libraries.
  description: |
    We aim to provide all of the power and control of the underlying library,
    but manage the gritty details as much as possible.

extra:
  recipe-maintainers:
    - hmaarrfk
